import type { Metadata } from "next";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ customerCategory: string }>;
}): Promise<Metadata> {
  const { customerCategory } = await params;

  function capitalizeFirstLetter(word: string): string {
    if (!word) return "";
    return word.charAt(0).toUpperCase() + word.slice(1);
  }

  return {
    title: `${capitalizeFirstLetter(customerCategory)} | TCS`,
    description: "Generated by create next app",
  };
}

export default async function Page({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return children;
}
