import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Home | TCS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <div className="">
          <header className="bg-primary-400 h-[60px] justify-items-center sticky">
            <div className="max-w-[1440px] w-full">
              <section className="flex justify-between items-center p-4">
                <p>
                  <Link href="/">
                    <strong>[Logo]</strong>
                  </Link>
                  <Link href="/men">
                    <strong>[Button: Men]</strong>
                  </Link>
                  <Link href="/women">
                    <strong>[Button: Women]</strong>
                  </Link>
                  <Link href="/kids">
                    <strong>[Button: Kids]</strong>
                  </Link>
                </p>
                <p className="absolute left-1/2 transform -translate-x-1/2"></p>
                <p>[Searchbar][Icon: Profile][Icon: Cart]</p>
              </section>
            </div>
          </header>
          <main className="justify-items-center">
            <div className="max-w-[1440px] w-full">{children}</div>
          </main>
          <footer className="justify-items-center bg-stone-500 h-[112px]">
            <div className="max-w-[1440px] w-full">Footer</div>
          </footer>
        </div>
      </body>
    </html>
  );
}
